#!/usr/bin/env python3
"""Export card names, flavour lines, rule text and icons to static/cards.js.

Single source of truth: the print generator's data is the web client's data, so
a card can never say one thing on cardboard and another on screen.
"""
import json
from pathlib import Path
import make_cards as M

ROOT = Path(__file__).resolve().parent.parent
cards = {k: {"ar": v[0], "en": v[1], "kind": v[2], "line": v[3], "rule": v[4]}
         for k, v in M.C.items()}
out = ROOT / "static" / "cards.js"
out.write_text(
    "// generated by scripts/export_web.py — do not edit\n"
    f"export const CARDS = {json.dumps(cards, ensure_ascii=False, indent=1)};\n"
    f"export const ICONS = {json.dumps(M.I, ensure_ascii=False, indent=1)};\n"
    f"export const FAMILY = {json.dumps({k: v[0] for k, v in M.ST.items()})};\n"
    f"export const GLOW = {json.dumps({k: v[2] for k, v in M.ST.items()})};\n"
    f"export const QTY = {json.dumps(M.QTY)};\n",
    encoding="utf-8")
print(f"wrote {out} ({len(cards)} cards, {len(M.I)} icons)")
