// generated by scripts/export_web.py — do not edit
export const CARDS = {
 "PASS": {
  "ar": "باص",
  "en": "PASS",
  "kind": "attack",
  "line": "الكرة تتنقل بينهم بهدوء... مفيش أي استعجال.",
  "rule": "يتلغى بـ اعتراض · تسلل · بلوك · فاول"
 },
 "INTERCEPTION": {
  "ar": "اعتراض",
  "en": "INTERCEPTION",
  "kind": "defense",
  "line": "ويقطعها!! في اللحظة المناسبة تمامًا!",
  "rule": "يوقف باص وأسيست · بياخد الاستحواذ"
 },
 "DRIBBLE": {
  "ar": "مراوغة",
  "en": "DRIBBLE",
  "kind": "attack",
  "line": "يراوغ الأول... والتاني!! والمدافع على الأرض!",
  "rule": "يتلغى بـ تدخل · فاول"
 },
 "TACKLE": {
  "ar": "تدخل",
  "en": "TACKLE",
  "kind": "defense",
  "line": "تدخل حاسم! الكرة أولًا ثم اللاعب!",
  "rule": "يوقف مراوغة · بياخد الاستحواذ"
 },
 "SHOT_GOAL": {
  "ar": "شوطة",
  "en": "SHOT GOAL",
  "kind": "attack",
  "line": "يسدد!! الكرة في الشبااااك!!",
  "rule": "نجحت = هدف · لازم تكون آخر كارت في السلسلة"
 },
 "GOAL_KEEPER": {
  "ar": "حارس مرمى",
  "en": "GOAL KEEPER",
  "kind": "defense",
  "line": "الحااارس!! ينقذ فريقه من هدف محقق!",
  "rule": "يوقف شوطة · الاستحواذ محايد"
 },
 "SUPER_SHOT": {
  "ar": "سوبر شوط",
  "en": "SUPER SHOT",
  "kind": "rare",
  "line": "قذيفة!!! والحارس لم يتحرك من مكانه!",
  "rule": "مالوش رد غير Block Save · ولا الفاول بيلغيه"
 },
 "BLOCK_SAVE": {
  "ar": "صد سوبر شوط",
  "en": "BLOCK SAVE",
  "kind": "rare",
  "line": "يبعدها بأطراف أصابعه!! إنقاذ كان مستحيلًا!",
  "rule": "الرد الوحيد على سوبر شوط · الاستحواذ محايد"
 },
 "ASSIST": {
  "ar": "أسيست",
  "en": "ASSIST",
  "kind": "attack",
  "line": "تمريرة سحرية!! تشق الدفاع نصفين!",
  "rule": "2v2 · نجح؟ الاستحواذ لزميلك ويفتح كارت الجول"
 },
 "GOAL": {
  "ar": "جول",
  "en": "GOAL",
  "kind": "attack",
  "line": "جوووول!! يا جماهير أون جول!! الشباك تهتز!",
  "rule": "2v2 · بعد أسيست زميلك بس · يتلغى بـ تسلل·VAR·أون جول"
 },
 "PENALTY": {
  "ar": "بنالتي",
  "en": "PENALTY",
  "kind": "rare",
  "line": "الحكم يشير إلى علامة الجزاء!! لا جدال فيها!",
  "rule": "العبها بعد فاول عليك = هدف · يتلغى بـ أون جول أو VAR"
 },
 "FOUL": {
  "ar": "فاول",
  "en": "FOUL",
  "kind": "defense",
  "line": "خطأ واضح ومتعمد! أوقف الهجمة بأي ثمن!",
  "rule": "يوقف باص·مراوغة·أسيست بس · الاستحواذ يرجع للمهاجم"
 },
 "OFFSIDE": {
  "ar": "تسلل",
  "en": "OFFSIDE",
  "kind": "defense",
  "line": "الراية مرفوعة! سابق للكرة بخطوة كاملة!",
  "rule": "يوقف باص·أسيست·شوطة·جول · بياخد الاستحواذ"
 },
 "BLOCK": {
  "ar": "بلوك",
  "en": "BLOCK",
  "kind": "defense",
  "line": "تصدى لها بجسده! والكرة تضيع بين الجميع!",
  "rule": "مود الحظ بس · يوقف باص وأسيست · بلا استحواذ"
 },
 "BLOCK_SHOT": {
  "ar": "صد تسديدة",
  "en": "BLOCK SHOT",
  "kind": "defense",
  "line": "يرتمي أمام الكرة!! ويمنع هدفًا محققًا!",
  "rule": "يوقف شوطة · الاستحواذ محايد"
 },
 "OWN_GOAL": {
  "ar": "هدف عكسي",
  "en": "OWN GOAL",
  "kind": "rare",
  "line": "لااااا!! في شباكه!! كارثة بكل المقاييس!",
  "rule": "النقطة تتحسب لك · يشتغل ضد شوطة·جول·بنالتي"
 },
 "CHAIN": {
  "ar": "استخلاص",
  "en": "CHAIN",
  "kind": "special",
  "line": "يستخلصها!! وينهي الهجمة قبل أن تبدأ!",
  "rule": "على كروت البناء بس · مبيلغيش أي كارت بيسجل"
 },
 "VAR": {
  "ar": "في إيه آر",
  "en": "VAR",
  "kind": "special",
  "line": "الحكم يتوجه إلى الشاشة... الملعب كله واقف!",
  "rule": "راجع هدف·بنالتي·تسلل · وش يأكد وضهر يلغي · مرة لكل حدث"
 },
 "RESHUFFLE": {
  "ar": "ريشافل",
  "en": "RESHUFFLE",
  "kind": "special",
  "line": "تغيير تكتيكي! المدرب غير مرتاح!",
  "rule": "بدّل كارتين من الديك · أو 2 مع زميلك في 2v2"
 },
 "END_MATCH": {
  "ar": "نهاية الماتش",
  "en": "END MATCH",
  "kind": "special",
  "line": "صافرة النهاية!! ولا وقت بدل ضائع لأحد!",
  "rule": "الماتش يخلص فورًا · متعادل؟ الفوز لخصمك"
 }
};
export const ICONS = {
 "PASS": "<circle cx=\"20\" cy=\"26\" r=\"6\"/><path d=\"M4 14h18M8 9h14\"/>",
 "INTERCEPTION": "<path d=\"M4 24h20\"/><path d=\"M18 18l6 6-6 6\"/><path d=\"M28 10v28\"/>",
 "DRIBBLE": "<path d=\"M4 34c6 0 6-10 12-10s6 10 12 10\"/><circle cx=\"32\" cy=\"12\" r=\"5\"/>",
 "TACKLE": "<path d=\"M4 32h14l4-8\"/><path d=\"M4 32l2 6h12\"/><circle cx=\"31\" cy=\"27\" r=\"6\"/>",
 "SHOT_GOAL": "<circle cx=\"14\" cy=\"24\" r=\"6\"/><path d=\"M26 12h12v24H26z\"/><path d=\"M32 12v24M26 24h12\"/>",
 "GOAL_KEEPER": "<path d=\"M10 34V18a4 4 0 018 0v-4a3 3 0 016 0v4a3 3 0 016 0v16z\"/><path d=\"M10 34h20\"/>",
 "SUPER_SHOT": "<circle cx=\"26\" cy=\"22\" r=\"7\"/><path d=\"M4 12l8 4-8 4M4 26l10 3-10 3\"/><path d=\"M36 10l-4 6h5l-5 8\"/>",
 "BLOCK_SAVE": "<path d=\"M8 36V22a3 3 0 016 0v-6a3 3 0 016 0v6\"/><circle cx=\"30\" cy=\"14\" r=\"6\"/><path d=\"M20 22h6\"/>",
 "ASSIST": "<path d=\"M4 34c4-16 16-22 28-22\"/><path d=\"M26 8l6 4-6 4\"/><circle cx=\"8\" cy=\"34\" r=\"4\"/>",
 "GOAL": "<path d=\"M6 12h28v24H6z\"/><path d=\"M14 12v24M22 12v24M30 12v24M6 20h28M6 28h28\"/><circle cx=\"20\" cy=\"24\" r=\"5\"/>",
 "PENALTY": "<circle cx=\"20\" cy=\"14\" r=\"6\"/><circle cx=\"20\" cy=\"34\" r=\"2\"/><path d=\"M20 20v10\" stroke-dasharray=\"3 3\"/>",
 "FOUL": "<path d=\"M8 18h16l8-4v14l-8-4H8z\"/><path d=\"M8 18a6 6 0 000 6\"/><path d=\"M32 8l4-4M36 14h6\"/>",
 "OFFSIDE": "<path d=\"M12 8v32\"/><path d=\"M12 10l20 5-20 5z\"/>",
 "BLOCK": "<path d=\"M10 10v28M20 10v28M30 10v28\"/><path d=\"M4 20h32\"/>",
 "BLOCK_SHOT": "<path d=\"M6 36c8-2 12-10 12-18\"/><path d=\"M18 18l8 4\"/><circle cx=\"32\" cy=\"14\" r=\"6\"/>",
 "OWN_GOAL": "<path d=\"M6 12h28v24H6z\"/><path d=\"M14 12v24M22 12v24M30 12v24\"/><path d=\"M34 24H16\"/><path d=\"M22 18l-6 6 6 6\"/>",
 "CHAIN": "<path d=\"M6 16h14M20 16l-5-4M20 16l-5 4\"/><path d=\"M34 30H20M20 30l5-4M20 30l5 4\"/>",
 "VAR": "<path d=\"M6 10h28v20H6z\"/><path d=\"M16 34h12\"/><path d=\"M17 16l8 4-8 4z\"/>",
 "RESHUFFLE": "<path d=\"M8 14h20M28 14l-5-4M28 14l-5 4\"/><path d=\"M32 30H12M12 30l5-4M12 30l5 4\"/><path d=\"M4 22h32\" stroke-dasharray=\"2 4\"/>",
 "END_MATCH": "<circle cx=\"20\" cy=\"22\" r=\"14\"/><path d=\"M20 12v10l7 5\"/><path d=\"M20 4v4\"/>"
};
export const FAMILY = {"attack": "#D7263D", "defense": "#1B4F72", "special": "#7D3C98", "rare": "#B8860B"};
export const GLOW = {"attack": "#FF6B35", "defense": "#2ECC71", "special": "#F1C40F", "rare": "#F1C40F"};
export const QTY = {"PASS": 15, "INTERCEPTION": 15, "DRIBBLE": 5, "TACKLE": 5, "SHOT_GOAL": 5, "GOAL_KEEPER": 5, "SUPER_SHOT": 2, "BLOCK_SAVE": 2, "ASSIST": 5, "GOAL": 5, "FOUL": 4, "BLOCK": 4, "BLOCK_SHOT": 3, "CHAIN": 2, "VAR": 2, "RESHUFFLE": 4, "END_MATCH": 1, "OWN_GOAL": 1, "OFFSIDE": 1, "PENALTY": 1};
